### PR TITLE
rtf_assemble.R

### PR DESCRIPTION
**Pull request by BrianLang**
Add rtf_assemble.R
- [x] officer:: 
- [x] no officer:: 
- [x] bulletproofing
- [x] devtools::document()

Add independent testing for rtf_assemble.R
- [x]  all arguments / bulletproofing.
- [x]  officer and non-officer implementation. 
- [ ]  check the use of per-page landscape setting in officer. 

Needed to run devtools::document, but I was getting a weird error. 
Looked into our github issue log and noticed a discussion on moving a dataset from `data/` to `R/`.

```r
> devtools::document()
ℹ Updating r2rtf documentation
ℹ Loading r2rtf
Writing NAMESPACE
Error: 'unicode_latex' is not an exported object from 'namespace:r2rtf'
```

It was caused by `/R/data.r` still including an entry for `unicode_latex` even though it's been removed from `data/`

### CODE REVIEW

**Comment by BrianLang** [comment]
would like to have a test for landscape/portait setting but haven't yet found how that's presented in a docx. maybe this is a good spot for snapshot testing.

also would like the example to be run-able. how should we create the rtfs to illustrate the function. It won't work with the vignette rtfs, since those aren't included in the package build.

**Comment by elong0527** [comment]
Let's merge the PR. 

Will great one PR to test if we like the idea of two functions. 

I will also create a separate PR for the test.

**Review by elong0527 — APPROVED** [review]

**Comment by elong0527** [comment]
@nanxstats , could you help us on this? Seems I am not authorized to merge the PR.

**Comment by nanxstats** [comment]
LGTM!

**Pull request merged**
