### PR TITLE
Rtf rich text

### LINKED ISSUE #112: Add inline text format
We need design a function that allow user to define inline text format. In r2rtf, we already have `rtf_text` for the whole text. It might be a wrapper function to allow inline format like markdown part in `gt` https://gt.rstudio.com/articles/intro-creating-gt-tables.html#adding-parts-to-this-simple-table

A missing piece is to enable selected color in the text as we will need it for mock table. 

```
#' Enable color for mockup table
#'
#' The function will automatically replace text between `<` and `>` into blue.
#'
#' @param text a string.
#'
#' @export
rtf_mock_color <- function(text) {

  # Match text in glue expression { }
  match_text <- stringr::str_match_all(text, "\\{\\s*(.*?)\\s*\\}")
  match_text <- stats::na.omit(do.call(rbind, match_text))

  # Convert to blue color
  .x <- vapply(match_text[, 2], function(x) {

    # borrow from r2rtf:::rtf_text logic.
    x <- paste0("{\\cf26 <", x, ">}")
  }, FUN.VALUE = "character")
  .x <- .x[unique(names(.x))]

  # Apply the change
  res <- vapply(text, function(x) glue::glue_data(.x, x), FUN.VALUE = "character")
  names(res) <- names(text)
  res
}
```

### LINKED ISSUE #185: Pkgdown fails on Master
**Describe the bug**
Currently the pkgdown action fails on master (pkgdown run #272). It throws an error that `tidyr` does not exist. `tidyr`, while being loaded by `library(tidyr)` in the vignettes, is not in the DESCRIPTION suggests field.

**Expected behavior**
pkgdown build actions should not fail on master.

**To reproduce**
Go to the GitHub actions and re-run the pkgdown build on master. 

**Session info**
CICD

**Additional context**
Found this out because #184 failed pkgdown build for the same reason, though the code does not touch anything related to vignettes.

### PR DESCRIPTION
**Pull request by BrianLang**
I've made the updates to remove dependencies and also resolved an issue with brace matching. 
Previously nesting of braces mixing rtf_text code like `{.emph text{^\\dagger}}` would end up matching the wrong braces and producing unexpected rtf output. Now it correctly resolves pairs of braces with FILO. 

closes #112 
closes #185

### CODE REVIEW

**Review by nanxstats — APPROVED** [review]
The patch looks neat! Thanks for improving on the previous implementation.

I only added a few minor fixes for code and documentation style to keep things consistent. Also used `@noRd` instead of `@keyword internal` to avoid generating `.Rd` files for internal functions, which is the existing convention in this package.

@elong0527 Any comments?

**Comment by BrianLang** [comment]
Thanks for the updates @nanxstats .
Do you have your own styler config? Or do you adapt these changes by hand? Agree that they look better.

**Comment by nanxstats** [comment]
> Thanks for the updates @nanxstats . Do you have your own styler config? Or do you adapt these changes by hand? Agree that they look better.

Good question! styler can apply the general style guide but it is not aggressive (probably to be on the safe side). For example, it doesn't know if new lines should be added or removed, and if words are properly stylized under the context.

In those cases, I just apply the more comprehensive guides from the original [tidyverse style guide](https://style.tidyverse.org/) manually when appropriate. That is ok because I think clean code / code style should be decided by humans ultimately, although automated rules surely help reduce manual work.

**Comment by elong0527** [comment]
Looks great! Thanks a lot for handling the task.

**Review by elong0527 — APPROVED** [review]

**Comment by BrianLang** [comment]
Thanks @nanxstats and @elong0527

**Comment by nanxstats** [comment]
@BrianLang This sounds like a excellent topic for an external blog post or vignette. It's super ✨visual✨

**Pull request merged**
